enableGlobalCache: true

enableTelemetry: false

nodeLinker: node-modules

packageExtensions:
  ts-jest@*:
    dependencies:
      jest-environment-node: "*"
      jest-util: "*"
    peerDependencies:
      jest-environment-node: "*"
      jest-util: "*"

tsEnableAutoTypes: true
